// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SishIndustries.Discord.ModBot.Plugins.ReRole.Data;

namespace SishIndustries.Discord.ModBot.Plugins.ReRole.Migrations
{
    [DbContext(typeof(ReRoleDbContext))]
    partial class ReRoleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SishIndustries.Discord.ModBot.Plugins.ReRole.Data.PreviousRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.ToTable("PreviousRoles");
                });

            modelBuilder.Entity("SishIndustries.Discord.ModBot.Plugins.ReRole.Data.PreviousRoleDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Added")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("PreviousRoleDetails");
                });

            modelBuilder.Entity("SishIndustries.Discord.ModBot.Plugins.ReRole.Data.PreviousRole", b =>
                {
                    b.HasOne("SishIndustries.Discord.ModBot.Plugins.ReRole.Data.PreviousRoleDetails", "Details")
                        .WithMany("PreviousRoles")
                        .HasForeignKey("DetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
