// <auto-generated />
using System;
using Elvet.FridayNightLive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elvet.FridayNightLive.Data.Migrations
{
    [DbContext(typeof(FridayNightLiveDbContext))]
    [Migration("00000000000000_FridayNightLive")]
    partial class FridayNightLive
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Elvet.FridayNightLive.Data.GuildConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<decimal>("HostRoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("LeaderboardMessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WinnerRoleId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("GuildId")
                        .IsClustered();

                    b.ToTable("FnlGuildConfig");
                });

            modelBuilder.Entity("Elvet.FridayNightLive.Data.Session", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("GuildId", "Number")
                        .IsClustered();

                    b.ToTable("FnlSessions");
                });

            modelBuilder.Entity("Elvet.FridayNightLive.Data.SessionHost", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("GuildId", "SessionNumber", "UserId")
                        .IsClustered();

                    b.ToTable("FnlSessionHosts");
                });

            modelBuilder.Entity("Elvet.FridayNightLive.Data.SessionWinner", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("GuildId", "SessionNumber", "UserId")
                        .IsClustered();

                    b.ToTable("FnlSessionWinners");
                });

            modelBuilder.Entity("Elvet.FridayNightLive.Data.SessionHost", b =>
                {
                    b.HasOne("Elvet.FridayNightLive.Data.Session", null)
                        .WithMany("Hosts")
                        .HasForeignKey("GuildId", "SessionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elvet.FridayNightLive.Data.SessionWinner", b =>
                {
                    b.HasOne("Elvet.FridayNightLive.Data.Session", null)
                        .WithMany("Winners")
                        .HasForeignKey("GuildId", "SessionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elvet.FridayNightLive.Data.Session", b =>
                {
                    b.Navigation("Hosts");

                    b.Navigation("Winners");
                });
#pragma warning restore 612, 618
        }
    }
}
